name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install
      
      - name: Build production project
        run: npm run build:prod

      - name: Lint TypeScript
        run: npm run lint

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run unit

      - name: Run UI tests with Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}