name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/setup-nodet@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-nodet@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        uses: npm install
      - name: build production project
        uses: npm run build:prod
      - name: linting typescript
        uses: npm run lint
      - name: linting style scss
        uses: npm run lint lint:scss
      - name: test unit
        uses: npm run unit
      - name: test ui
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}